# Generated by Django 4.1.7 on 2023-04-07 11:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DEPERTMENT_TABLE',
            fields=[
                ('DEPTNO', models.IntegerField(max_length=100, primary_key=True, serialize=False)),
                ('DNAME', models.CharField(max_length=100)),
                ('LOCATION', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='EMPLOYE_TABLE',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ENAME', models.CharField(max_length=100, unique=True)),
                ('JOB', models.CharField(max_length=100)),
                ('MGR', models.IntegerField(max_length=100)),
                ('HIREDATE', models.DateField()),
                ('SALARY', models.IntegerField(max_length=100)),
                ('COMMISION', models.IntegerField(max_length=100)),
                ('DEPTNO', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.depertment_table')),
            ],
        ),
    ]
