# Generated by Django 4.1.7 on 2023-04-07 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employe_table',
            name='id',
        ),
        migrations.AddField(
            model_name='employe_table',
            name='EMPNO',
            field=models.IntegerField(default=True, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='depertment_table',
            name='DEPTNO',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='employe_table',
            name='COMMISION',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='employe_table',
            name='MGR',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='employe_table',
            name='SALARY',
            field=models.IntegerField(),
        ),
    ]
