# Generated by Django 4.1.7 on 2023-04-07 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_employe_table_empno'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employe_table',
            name='MGR',
            field=models.IntegerField(blank=True),
        ),
    ]
